### ISSUE TITLE
Setup production build to setup the production server

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr#42]
We are currently building production by hand. We should integrate production deployment into the CI process. This would likely look like the following:

- [ ] Add a "production" section to the circle.yml file that pushes the ```master``` branch to our production machine.  Something along the lines of:
```yaml
  production:
    branch: master
    commands:
      - npm rebuild node-sass
      - DS_ENV=staging yarn run build
      - scp -r dist username@hostname:/path-to-static-file-location/
```
- [ ] Create a user on the production server that is locked down to only be able to add files to the static code directory.
- [ ] Add an [SSH key and configure permissions](https://circleci.com/docs/1.0/configuration/#ssh-keys) so CircleCI can push to the production server as the locked down user
- [ ] Modify the current staging build rule to build from a ```development``` branch.
